name: Run Ghost Inspector test suite

on: 
  workflow_call:
    secrets:
      SUITE_ID:
        required: true
      API_KEY:
        required: true

jobs:
  ghost-inspector-run:
    runs-on: ubuntu-latest
    steps:
      - name: Run test suite
        run: |
          curl "https://api.ghostinspector.com/v1/suites/${{ secrets.SUITE_ID }}/execute/?apiKey=${{ secrets.API_KEY }}" -m 1200
      - name: Get suite result
        shell: bash
        run: |
          response=$(curl "https://api.ghostinspector.com/v1/suites/${{ secrets.SUITE_ID }}/results/?apiKey=${{ secrets.API_KEY }}&count=1")
          name=$(jq '.data[0].name' <<< $response )
          testResult=$(jq '.data[0].passing' <<< $response)
          screenshotResult=$(jq '.data[0].screenshotComparePassing' <<< $response)  # Can be null.
          failingCount=$(jq '.data[0].countFailing' <<< $response)
          passingCount=$(jq '.data[0].countPassing' <<< $response)
          failingScreenshotCount=$(jq '.data[0].countScreenshotCompareFailing' <<< $response)
          passingScreenshotCount=$(jq '.data[0].countScreenshotComparePassing' <<< $response)
          if [[ $testResult == 'true' ]] && [[ $screenshotResult == 'true' || $screenshotResult == 'null' ]]; then
            echo "Suite ${name} passing: ${passingCount} tests passed, ${passingScreenshotCount} screenshot comparisons passed, 0 tests/screenshots failed"
            exit 0
          fi
          echo "Suite ${name} failing: ${passingCount} tests passed, ${passingScreenshotCount} screenshot comparisons passed, ${failingCount} tests failed, ${failingScreenshotCount} screenshot comparisons failed"
          exit 1
